# Initialization file for the KUKA Fast Research Interface of the Light-Weight Robot IV

[RobotName]
Name=Right

[Priorities]
#Priority range: 1..63
KRCCommunicationThread=60
TimerThread=55
MainThread=50
OutputConsoleThread=5

[ControlValues]
# Cycle time in seconds
CycleTime=0.002

[Logging]
NumberOfLoggingFileEntries=160000
LoggingPath=C:\\Users\\FRI\\Documents\\fri_projekty\\lwolinski\\FRILibrary\\out
LoggingFileName=LWR-Scope.dat